EIP712 Update to support multiple transactions
Kava-Labs/ethermint pull request #11
Opened 2022-06-02 16:14 UTC by DracoLi

Closes: #XXX

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2022-07-21 15:04 UTC, DracoLi commented on x/evm/types/params_test.go
> +			true,
noticed the original test was wrong so updated it here to properly test its invalid case.

2022-07-25 23:15 UTC, rhuairahrighairidh requested changes
nice, the simplifications look good

2022-07-26 14:57 UTC, DracoLi commented on app/ante/ante_test.go
> +	suite.app.EvmKeeper.SetParams(suite.ctx, params)
we have one on kava that sends cdp, hard, and convert erc20 msgs. Are you referring to specifically sending a send and delegate too?

2022-07-26 14:57 UTC, DracoLi commented on ethereum/eip712/eip712.go
> +func EIP712SignBytes(chainID string, accnum, sequence, timeout uint64, fee legacytx.StdFee, msgs []sdk.Msg, memo string) []byte {
:+1:

2022-07-26 15:01 UTC, DracoLi commented on ethereum/eip712/eip712.go
> +		legacyMsgType := legacyMsg.Type()
great idea. I'll update to use the proto name

2022-07-27 20:43 UTC, rhuairahrighairidh approved these changes
looks good

2022-07-28 20:04 UTC, merged